### ISSUE TITLE
Alternative zu virtualbox

### ISSUE THREAD

**Issue by KampfCaspar** [ccc-ch/ccc-ch.ch#1]
Wie wäre es mit einer Alternative zu Virtualbox, die etwas weniger riesig ist... docker oder so?

Selbst Windoof-User können ja docker mit vagrant nutzen!

**Comment by dbrgn** [comment]
Wär was.

Auf der anderen Seite ist Virtualbox einerseits einfach zu installieren (v.a. einfacher als Docker).

Zudem braucht man die VM gar nicht umbedingt. Lokal die Abhängigkeiten mit pip installieren reicht auch.

**Comment by KampfCaspar** [comment]
#2
