### ISSUE TITLE
20min-Überwachungsanhänger-pdf missing

### ISSUE THREAD

**Issue by gnurbs** [ccc-ch/ccc-ch.ch#138]
on the server, there's no file:

`https://www.ccc-ch.ch/articles/20180412-20min.pdf.ch`
so the url is 404 by consequence.

This could be another deployment issue: it's in the repo.

**Comment by dbrgn** [comment]
```
rsync: failed to set permissions on "/.../swiss-chaos.ch/htdocs/articles": Operation not permitted (1)
articles/20180412-20min.pdf
```

The `articles` directory has the owner `tobias` and no group write bit. Who's tobias? Probably he didn't set his umask correctly :confused:

**Comment by gnurbs** [comment]
that would be @keachi: set the bit please

**Comment by dbrgn** [comment]
@keachi also, take a look at https://github.com/ccc-ch/ccc-ch.ch#deployment and add `umask 022` to your `~/.profile` :slightly_smiling_face:

**Comment by keachi** [comment]
I don't even know if my login still works and which key I used last time, that must be more than a year ago. I wasn't deploying for a long time. But I will not change my umask for this repository, so I just don't deploy. IMHO fix it on the server side or create a service account with restricted rsync.

**Comment by dbrgn** [comment]
@keachi I'm not sure if you misunderstood me, but you would have to change your umask on the server of course, not on your local machine :slightly_smiling_face:

**Comment by keachi** [comment]
@dbrgn oh I see, there is a fix for the chmod in the rsync upload target. Sorry didn't know that, normally the rsync upload will fail. I found some login information and checked my umask:
```
$ umask
0002
$ ls -la .profile 
-rw-r--r-- 1 tobias webadmins 674 Nov 21  2015 .profile
```
So, no restrictive umask since 2015-11-21 ;-)

**Comment by keachi** [comment]
I fixed the permissions on the webserver for this special directory.

**Comment by dbrgn** [comment]
Thanks! I could deploy and https://www.ccc-ch.ch/articles/20180412-20min.pdf works now :)

**Comment by keachi** [comment]
Still, there should be an enforcing or a restricted service account on the server. Or even better an automatic deployment.
