### ISSUE TITLE
Pelican Configuration

### ISSUE THREAD

**Issue by dbrgn** [ccc-ch/ccc-ch.ch#14]
Generating the website content does not work for me:

```
git clone https://github.com/ccc-ch/ccc-ch.ch
cd ccc-ch.ch
virtualenv -p /usr/bin/python3 VENV
source VENV/bin/activate
pip install pelican==3.6.3
make html
```

This results in:

```
Done: Processed 0 articles, 0 drafts, 0 pages and 0 hidden pages in 0.10 seconds.
Done: Processed 0 articles, 0 drafts, 0 pages and 0 hidden pages in 0.17 seconds.
Done: Processed 0 articles, 0 drafts, 0 pages and 0 hidden pages in 0.26 seconds.
```

Obri and @The-Compiler report the same.

@2-B and @bashvi, how do you develop? Maybe you're keeping some files locally but not in the repo?

**Comment by The-Compiler** [comment]
It seems to work with Pelican 3.6.3 from the Debian repos?!

```
Done: Processed 0 articles, 0 drafts, 1 page and 15 hidden pages in 0.21 seconds.
Done: Processed 0 articles, 0 drafts, 16 pages and 0 hidden pages in 0.42 seconds.
Done: Processed 0 articles, 0 drafts, 16 pages and 0 hidden pages in 0.80 seconds.
```

**Comment by 2-B** [comment]
I have nothing locally. I use the pelican from the Debian repos, but in version 3.6.3. I will test it with pelican from pip tomorrow.

**Comment by The-Compiler** [comment]
We just figured it out in the `#ccc` IRC channel - it was indeed `markdown` missing.
