### ISSUE TITLE
Newsfeeds

### ISSUE THREAD

**Issue by dbrgn** [ccc-ch/ccc-ch.ch#18]
Wir sollten bei Gelegenheit alle News-artigen Seiten (z.B. Pressespiegel, Pressemitteilungen, Protokolle, etc) als Artikel implementieren, statt als Seiten. Dann ist es möglich, Newsfeeds (RSS / Atom) dafür zu generieren.

Vgl Mailinglisten-Diskussion von heute.

**Comment by bashvi** [comment]
Ich hab' das hier mal versucht:

  https://github.com/bashvi/ccc-ch.ch/tree/news_and_rss_feed

Habe aber leier atm kein Pelican um das zu testen... Kannst ja mal gucken ob es das macht was es soll.

**Comment by dbrgn** [comment]
Funktioniert prinzipiell. Wir müssen das List-Template aber noch überarbeiten. Am besten jeweils nur das Datum und den Titel auflisten. Standardmässig wird der gesamte Content angezeigt.

Die Feeds funktionieren anscheinend noch nicht.

Ahja, bin mir gerade nicht mehr sicher: Ist es standardmässig möglich, mehrere Feeds / Content Kategorien zu machen? Zum Beispiel Pressemitteilungen, News und Pressespiegel.

**Comment by 2-B** [comment]
Das waer eben auch das gewesen, was ich moechte. Daher muss wohl noch ein Pelican plugin oder so dazu, weil standardmaessig kennts glaubs nicht mehr als eine Feeds Seite. Aber werd heute dann mal ein bisschen suchen.

**Comment by bashvi** [comment]
Dass es den ganzen Content auflistet liegt glaubs daran, dass die Artikel kein "Summary:" haben...
Wenn wir gar kein summary wollen, dann reichts vermutlich die Zeilen 20-23 in der Date theme/templates/news.html aus zu kommentieren.

**Comment by bashvi** [comment]
Also innerhalb der News Seiten sollte es, denke ich, kein Problem sein 'Kategorien' zu machen. Gibt ja bereits ein category.html template. Man muesste einfach den Artikeln eine Category zuweisen.
Fuer die FEEDs gibts CATEGORY_FEED...

**Comment by dbrgn** [comment]
Ah, alles klar! :)
