### ISSUE TITLE
dropdown menu "ccc-ch" needs javascript

### ISSUE THREAD

**Issue by gnurbs** [ccc-ch/ccc-ch.ch#24]
navigation should work without JS, central drop-down menu "CCC-CH" does not. 
I guess this could be addressed when implementing Jan's theme?

**Comment by dbrgn** [comment]
Yes, probably. Basically we need to show the dropdown by default and hide it using JS.

(I'm not even sure if Jan's theme contains dropdowns or not.)

**Comment by NiklausHofer** [comment]
Kann bitte mal einer den Issue schliessen. Ist ja schon seit einiger Zeit behoben...
