### ISSUE TITLE
Shariff Buttons to share content.

### ISSUE THREAD

**Issue by bashvi** [ccc-ch/ccc-ch.ch#27]
Add "Share on $SOCIALNETWORK" buttons to the website.
To avoid tracking of our users, we can use the Heise.de Shariff buttons which do not load any Facebook/Twitter/whatnot content until clicked by the user:

  https://github.com/heiseonline/shariff

**Comment by dbrgn** [comment]
Do you think people actually use these buttons? I never use them, I simply copy-paste the URL. Much simpler.

**Comment by ravench** [comment]
Same here.

**Comment by xtaran** [comment]
Those buttons are at least preferable over the original Like/Whatever buttons which usually contain tracking code. The question is: Do we need such buttons at all, especially after the current discussion about facebook in general on the mailing list.

**Comment by bashvi** [comment]
When we had the discussion about social networks at the recent gettogether, the buttons were seen as a viable alternative by some people (including me). It allows the users of social networks to share and distribute our content without us having to be directly involved in the process. The Shariff buttons are non-tracking so we don't expose our users to any risk.
So the question at hand is whether we want to completely boycott Faceboot/Twitter/Whatnot or not.
Maybe we should leave the issue open and have a discussion about this very matter on the mailing list. If in doubt, we can always have a vote on it at the next gettogether and leave the pull request open until then...

**Comment by dbrgn** [comment]
The buttons are already merged. If someone complains, we can discuss them on the mailing list.
