### ISSUE TITLE
Medienspiegel as category

### ISSUE THREAD

**Issue by dbrgn** [ccc-ch/ccc-ch.ch#30]
Can we make the Medienspiegel a category, similar to the Medienmitteilungen that @bashvi just did?

The cool things about it would be:

- People can subscribe to the medienspiegel newsfeed
- There's a file per entry, so we can script the creation of these items
- In that scripting step, we could also convert the website to a PDF with something like [wkhtmltopdf](http://wkhtmltopdf.org/) (thx @The-Compiler) and attach it to the entry, with a nice auto-generated PDF logo per entry on the overview page.
- We can actually set things like the newspaper name, the original date published and the date added as metadata entries

Downsides:

- Adding new medienspiegel entries gets more complicated than before.

**Comment by 2-B** [comment]
Merged

**Comment by bashvi** [comment]
Kann man den schliessen?

**Comment by dbrgn** [comment]
Ja.
