### ISSUE TITLE
Pressreview -> Pressespiegel

### ISSUE THREAD

**Issue by The-Compiler** [ccc-ch/ccc-ch.ch#47]
Ich hab auf die Schnelle grad nicht begriffen, wie ich das ändere - aber IMHO sollte da im Menü "Pressespiegel" oder sowas statt "Pressreview" stehen - ist so ein Aussenseiter als englisches Wort :wink:

**Comment by dbrgn** [comment]
Guter Punkt. Ich dachte eigentlich, dass das abhängig ist vom "Title" tag in `content/pages/de/pressreview.md`, aber anscheinend nicht...

**Comment by dbrgn** [comment]
Ah nein, die Seite ist gar nicht mehr aktiv. Die Konfiguration ist in `pelicanconf.py`. Ich werde gleich einen PR erstellen.
