### ISSUE TITLE
Zwei docker container? einer reicht...

### ISSUE THREAD

**Issue by KampfCaspar** [ccc-ch/ccc-ch.ch#5]
Ich weiss und bin einverstanden, dass in Docker grundsätzlich nur eine 'Applikation' pro Container laufen sollte. Für eine einfache dev Umgebung sind ZWEI container 'nur' für ein separates sass watch aber nicht notwendig, IMHO.

Gibt es einen speziellen Grund, wieso zwei?

**Comment by dbrgn** [comment]
Bin noch etwas am herumexperimentieren damit. Ist noch nicht ganz fertig.

Ohne Init-Prozess (man könnte natürlich auch Supervisor nehmen) kann man ja pro Container nur 1 Task ausführen. Deshalb dachte ich dass das eine Notwendigkeit ist, bzw die "saubere" Variante darstellt.

So bleiben die beiden Container schlank. Die Dependencies sind ja auch recht unterschiedlich. Vagrant kann gut beide Varianten verwalten. Zudem ist Grunt / SASS für viele Zwecke auch gar nicht nötig.

Fändest du es besser wenn es nur einen Container gäbe? Falls ja, wie würdest du das umsetzen?

**Comment by KampfCaspar** [comment]
Du hast einen Container-Init-Prozess - aber der kann selbstverständlich mehrere Prozesse starten. Beim stoppen des Containers verschwinden einfach alle Prozesse - beim neu starten wird der Container-Init neu gestartet.

Supervisor et al brauchst Du erst, wenn Du auch tatsächlich Kontrolle brauchst (restarts und so).

Für so kleine Development Container kannst Du im 'run.sh' einfach alles starten, was Du brauchst... Quick&Dirty

**Comment by dbrgn** [comment]
Stimmt auch wieder. OK, werde das bei Gelegenheit "rückbauen" :)
