### ISSUE TITLE
video einbinden?

### ISSUE THREAD

**Issue by gnurbs** [ccc-ch/ccc-ch.ch#67]
kriegen wir es bis Dienstag Nachmittag hin, ein Video einzubinden? Die DigiGes wird einen Kurzfilm (eine Minute) veröffentlichen, um das Büpf-Referendum zu unterstützen. Prinzipiell kann man das von vimeo oder youtube einbinden, aber aus Privacy-Gründen wär es natürlich cooler, das mit eigener Technik zu machen.

**Comment by dbrgn** [comment]
Klar, etwas in der Art sollte funktionieren, da Markdown direkt inline HTML unterstützt:

```html
<video src="videofile.ogg" preload="metadata" controls>
Sorry, Ihr Browser unterstützt die Wiedergabe von Videos noch nicht.
Sie können es jedoch auch <a href="videofile.ogg">herunterladen</a> und mit
einem beliebigen Videoplayer anschauen!
</video>
```

Ich kann das Video sonst aufschalten sobald wir es haben. Aber jemand anderes müsste Text usw drumherum liefern.

**Comment by gnurbs** [comment]
done
